#!/bin/bash

echo "=========================================="
echo "  🔐 Verificar Secrets de GitHub"
echo "=========================================="
echo ""
echo "📋 Esta herramienta te ayuda a verificar que los secrets"
echo "   en GitHub estén configurados correctamente."
echo ""
echo "⚠️  NOTA: No puedo leer los valores reales de los secrets"
echo "   desde aquí, pero puedo ayudarte a verificar manualmente."
echo ""
echo "=========================================="
echo "  📋 SECRETS REQUERIDOS"
echo "=========================================="
echo ""

echo "1. VPS_HOST"
echo "   ✅ Debe estar configurado"
echo "   📝 Valor esperado: 72.60.63.240"
echo "   📝 Tipo: IP del servidor VPS"
echo "   🔗 Verifica en: Settings → Secrets → Actions → VPS_HOST"
echo ""

echo "2. VPS_USER"
echo "   ✅ Debe estar configurado"
echo "   📝 Valor esperado: root"
echo "   📝 Tipo: Usuario SSH"
echo "   🔗 Verifica en: Settings → Secrets → Actions → VPS_USER"
echo ""

echo "3. VPS_SSH_PASSWORD"
echo "   ✅ DEBE estar configurado"
echo "   📝 Valor esperado: Aar-Beto-2026"
echo "   📝 Longitud: 13 caracteres"
echo "   📝 Primer carácter: A"
echo "   📝 Último carácter: 6"
echo "   📝 Caracteres especiales: - (guión)"
echo "   ⚠️  Sin espacios al inicio o final"
echo "   ⚠️  Sin comillas alrededor"
echo "   🔗 Verifica en: Settings → Secrets → Actions → VPS_SSH_PASSWORD"
echo ""

echo "=========================================="
echo "  📋 SECRETS OPCIONALES"
echo "=========================================="
echo ""

echo "4. VPS_SSH_KEY"
echo "   ⚪ Opcional (si usas contraseña, no es necesario)"
echo "   📝 Tipo: Clave SSH privada completa"
echo "   📝 Debe incluir: -----BEGIN ... KEY-----"
echo "   🔗 Verifica en: Settings → Secrets → Actions → VPS_SSH_KEY"
echo ""

echo "=========================================="
echo "  ✅ CÓMO VERIFICAR EN GITHUB"
echo "=========================================="
echo ""

echo "1. Ve a tu repositorio en GitHub"
echo "2. Click en 'Settings' (arriba del repositorio)"
echo "3. En el menú lateral, busca 'Secrets and variables'"
echo "4. Click en 'Actions'"
echo "5. Revisa la lista de 'Repository secrets'"
echo ""
echo "Para cada secret:"
echo "  - Verifica que existe en la lista"
echo "  - Si existe, click para ver detalles (no verás el valor por seguridad)"
echo "  - Si no existe, click 'New repository secret' para crearlo"
echo ""

echo "=========================================="
echo "  🧪 VERIFICACIÓN AUTOMÁTICA"
echo "=========================================="
echo ""

echo "Para verificar automáticamente los secrets, ejecuta el workflow:"
echo ""
echo "  1. Ve a 'Actions' en GitHub"
echo "  2. Busca 'Verify All GitHub Secrets'"
echo "  3. Click 'Run workflow'"
echo "  4. Revisa los resultados"
echo ""

echo "=========================================="
echo "  📝 VALORES ESPERADOS"
echo "=========================================="
echo ""

echo "VPS_HOST:"
echo "  Valor: 72.60.63.240"
echo "  Tipo: IP del servidor"
echo ""

echo "VPS_USER:"
echo "  Valor: root"
echo "  Tipo: Usuario SSH"
echo ""

echo "VPS_SSH_PASSWORD:"
echo "  Valor: Aar-Beto-2026"
echo "  Longitud: 13 caracteres"
echo "  Formato: A-a-B-e-t-o-2-0-2-6"
echo "  Primer carácter: A"
echo "  Último carácter: 6"
echo "  Caracteres especiales: - (guión)"
echo ""

echo "=========================================="
echo "  🔧 SI NECESITAS ACTUALIZAR"
echo "=========================================="
echo ""

echo "Para actualizar un secret:"
echo ""
echo "1. Ve a: Settings → Secrets → Actions"
echo "2. Busca el secret que quieres actualizar"
echo "3. Click en el secret"
echo "4. Click en 'Update'"
echo "5. Pega el nuevo valor"
echo "6. Click 'Update secret'"
echo ""

echo "=========================================="

